package Bio::Phylo::PhyloBank::Model::ORMTreeBASE;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Bio::Phylo::TreeBASE',    
);

=head1 NAME

Bio::Phylo::PhyloBank::Model::ORMTreeBASE - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Bio::Phylo::PhyloBank>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Bio::Phylo::TreeBASE>.
This model is built around the TreeBASE ORM mapping as per the treebase-core
source code, i.e.
L<http://treebase.svn.sourceforge.net/viewvc/treebase/trunk/treebase-core/src/main/perl/>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Rutger Vos

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
